### ISSUE TITLE
Missing txt file?

### ISSUE THREAD

**Issue by leonsegal** [devinherron/vampire#26]
I keep getting the error: `2024/08/23 18:44:20 open ./assets/_Thousand Year Old Vampire.txt: no such file or directory`

**Comment by devinherron** [comment]
You have to supply that file yourself, since its copyrighted. It comes with the digital copy of the game.

**Comment by leonsegal** [comment]
ah ok: I am trying to source a game in the uk

**Comment by devinherron** [comment]
I'll update the readme to mention it, though I haven't really worked on this project in a long time.
